### ISSUE TITLE
Jest doesn't exit without --forceExit flag

### ISSUE THREAD

**Issue by joshuap** [honeybadger-io/honeybadger-vue#762]
See this commit:

https://github.com/honeybadger-io/honeybadger-vue/commit/b4f0e6697c8d10fbec40c84aee9172d3c053efb9

I'd like to revert that, and fix the real issue. This didn't happen in the past, so maybe something changed in a dependabot update.

**Comment by incredimike** [comment]
Quick update: I've poked at this few times in the last 3 weeks. Still in progress.

**Comment by incredimike** [comment]
First I wanted to understand where the 403 error messages were coming from. I took the following (unsuccessful) steps to mitigate the messages:
- Tested extending the `setTimeout` on `afterNotify` callback.
- Tested converting afterNofify  to promises. 
- Finally tested an adding additional setTimeout for done() call, to provide time for the call to HB to resolve completely before running done().
All resulted in the same error messages being output.

Then it clicked that the messages are the results from the real API calls made to HB when the tests are run. I wanted to check if we could make jest wait until those API calls were complete before running `done()`/exiting. However, it doesn't look like we can capture that HB API call (using promises, for example) without rewriting honeybadger-js.

All that said, we MIGHT be able to avoid issues with open handles by artificially extending the time before we call `done()` in the `afterNotify` function by wrapping it in a `setTimeout`.

It still feels like a shot in the dark since I can't recreate locally.

**Comment by incredimike** [comment]
I attempted to recreate the original issue in Github Actions
https://github.com/honeybadger-io/honeybadger-vue/runs/2250182597

Looks like the original configuration may be working without code edits.

**Comment by joshuap** [comment]
@incredimike do you know where the tests are making live calls to the API during the test run? That shouldn't be happening in the unit tests.

**Comment by incredimike** [comment]
@joshuap Yeah, I was going to ask about that... I was debugging the `constructor.config.errorHandler` call in https://github.com/honeybadger-io/honeybadger-vue/blob/a1661d9cb5d28b161de3cda51b95a87489a8851b/test/unit/specs/HoneyBadgerVue.spec.js#L105

It makes real calls to the API when the error handler is set. I checked this by editing the compiled `node_modules\@honeybadger-io\js\dist\server\honeybadger.js` and sprinkling in a few debug statements in the `__send` and `getStats` functions.

**Comment by joshuap** [comment]
> @joshuap Yeah, I was going to ask about that... I was debugging the `constructor.config.errorHandler` call in
> 
> https://github.com/honeybadger-io/honeybadger-vue/blob/a1661d9cb5d28b161de3cda51b95a87489a8851b/test/unit/specs/HoneyBadgerVue.spec.js#L105
> 
> It makes real calls to the API when the error handler is set. I checked this by editing the compiled `node_modules\@honeybadger-io\js\dist\server\honeybadger.js` and sprinkling in a few debug statements in the `__send` and `getStats` functions.
> 
> This is one example. The final 3 tests (~lines 100-133) trigger the 3 errors you see.

Thanks for the research! I spent some time with it today and found that it was importing the server module instead of the browser one, and thus the XMLHttp stub wasn't working. So that solves one issue.

I removed the `--forceExit` flag in package.json and the builds are all working in CI, but locally jest still hangs when I run `npm test`. The tests complete successfully with no warnings, but I have to `ctrl+c` to exit. Can you pull from master and see if it's the same on your machine @incredimike?

**Comment by joshuap** [comment]
Where this stands:

> I removed the --forceExit flag in package.json and the builds are all working in CI, but locally jest still hangs when I run npm test. The tests complete successfully with no warnings, but I have to ctrl+c to exit.

I need someone to verify that they are seeing the same behavior as me when running the tests locally.

**Comment by ParamagicDev** [comment]
@joshuap I cannot reproduce this locally. I ran the unit tests without issues.

Im on:

MacOS Big Sur
Node Version 14.15.1

If youre still hitting this issue, could you try running Jest with the `--detectOpenHandles` ?

https://jestjs.io/docs/cli#--detectopenhandles

This is the recommended debugging step for this issue.

Side note:

 I couldnt get the E2E tests to run locally. Heres the steps I followed to try to fix it:

First issue I bumped into was the Vue loader plugin. Thats fixed by doing this: https://github.com/vuejs/vue-loader/issues/1688#issuecomment-647994678

However, fixing the path causes another error which is solved here: https://stackoverflow.com/questions/64117281/error-vue-loader-requires-vue-compiler-sfc-to-be-present-in-the-dependency-tr

HOWEVER, this then required Vue 3.1.4 which obviously we dont want....so yea

**Comment by joshuap** [comment]
@ParamagicDev thanks for checking this! I just tried and it didn't reproduce for me either... 🤷 I'll close this before it comes back. 😂

Regarding the E2E tests, it sounds like maybe we'll need to fix that as a part of #779. I'm still not totally sure of the best way to support both Vue 2 and Vue 3—currently Vue 3 support is on a branch, but the tests need to be updated.
